### ISSUE TITLE
Problems with numpy version number <1.8

### ISSUE THREAD

**Issue by chaosink** [alexjc/shadertoy-render#1]
I can watch the effect. But when it's over nothing is created.

**Comment by alexjc** [comment]
It's automatically created and overwritten based on the command line argument.

Do you have `ffmpeg` installed in your path?

**Comment by chaosink** [comment]
Yes, I have installed ffmpeg.

**Comment by chaosink** [comment]
```shell
➜  shadertoy-render git:(master) ✗ ffmpeg -h      
ffmpeg version 2.7.1 Copyright (c) 2000-2015 the FFmpeg developers
  built with gcc 4.8 (Ubuntu 4.8.4-2ubuntu1~14.04)
  configuration: 
  libavutil      54. 27.100 / 54. 27.100
  libavcodec     56. 41.100 / 56. 41.100
  libavformat    56. 36.100 / 56. 36.100
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 16.101 /  5. 16.101
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  2.100 /  1.  2.100
Hyper fast Audio and Video encoder
```

**Comment by chaosink** [comment]
I downloaded the tarball which is of the newest version from the official website and compiled it.

**Comment by alexjc** [comment]
What command line are you using exactly, and what's the size of the output file you specify?

**Comment by chaosink** [comment]
```shell
➜  shadertoy-render git:(master) ✗ python shadertoy-render.py Seascape.glsl Seascape.mp4 
```
```shell
➜  shadertoy-render git:(master) ✗ python shadertoy-render.py Seascape.glsl Seascape.mp4 --size 1920x1080 --duration 5.0 --rate 60
```
It seems that the option `--duration 5.0` has no effect.

**Comment by alexjc** [comment]
Is the `Seascape.mp4` file ever created?

**Comment by alexjc** [comment]
The only idea I have is for you to disable `-loglevel panic` in the call of `ffmpeg` and see what the error is, if there is any.

**Comment by chaosink** [comment]
There is no `Seascape.mp4` in the directory before.
Here are more information of the procedure.
```shell
➜  shadertoy-render git:(master) ✗ ls
docs  glsl  LICENSE  README.rst  Seascape.glsl  shadertoy-render.py
➜  shadertoy-render git:(master) ✗ python shadertoy-render.py Seascape.glsl Seascape.mp4 --size 1920x1080 --duration 5.0 --rate 10
WARNING: Traceback (most recent call last):
  File "shadertoy-render.py", line 167, in <module>
    canvas.app.run()
  File "/usr/local/lib/python2.7/dist-packages/vispy/app/application.py", line 123, in run
    return self._backend._vispy_run()
  File "/usr/local/lib/python2.7/dist-packages/vispy/app/backends/_glfw.py", line 194, in _vispy_run
    self._vispy_process_events()
  File "/usr/local/lib/python2.7/dist-packages/vispy/app/backends/_glfw.py", line 188, in _vispy_process_events
    win._on_draw()
  File "/usr/local/lib/python2.7/dist-packages/vispy/app/backends/_glfw.py", line 407, in _on_draw
    self._vispy_canvas.events.draw(region=None)  # (0, 0, w, h))
  File "/usr/local/lib/python2.7/dist-packages/vispy/util/event.py", line 436, in __call__
    self._invoke_callback(cb, event)
  File "/usr/local/lib/python2.7/dist-packages/vispy/util/event.py", line 452, in _invoke_callback
    self, cb_event=(cb, event))
  << caught exception here: >>
  File "/usr/local/lib/python2.7/dist-packages/vispy/util/event.py", line 448, in _invoke_callback
    cb(event)
  File "shadertoy-render.py", line 104, in on_draw
    self._stdout.write(framebuffer.tobytes())
AttributeError: 'numpy.ndarray' object has no attribute 'tobytes'
ERROR: Invoking <bound method RenderingCanvas.on_draw of <RenderingCanvas (Glfw) at 0x7f6cb1f7cc50>> for DrawEvent
ERROR: Invoking <bound method RenderingCanvas.on_draw of <RenderingCanvas (Glfw) at 0x7f6cb1f7cc50>> repeat 2
ERROR: Invoking <bound method RenderingCanvas.on_draw of <RenderingCanvas (Glfw) at 0x7f6cb1f7cc50>> repeat 3
ERROR: Invoking <bound method RenderingCanvas.on_draw of <RenderingCanvas (Glfw) at 0x7f6cb1f7cc50>> repeat 4
ERROR: Invoking <bound method RenderingCanvas.on_draw of <RenderingCanvas (Glfw) at 0x7f6cb1f7cc50>> repeat 5
ERROR: Invoking <bound method RenderingCanvas.on_draw of <RenderingCanvas (Glfw) at 0x7f6cb1f7cc50>> repeat 6
ERROR: Invoking <bound method RenderingCanvas.on_draw of <RenderingCanvas (Glfw) at 0x7f6cb1f7cc50>> repeat 7
ERROR: Invoking <bound method RenderingCanvas.on_draw of <RenderingCanvas (Glfw) at 0x7f6cb1f7cc50>> repeat 8
ERROR: Invoking <bound method RenderingCanvas.on_draw of <RenderingCanvas (Glfw) at 0x7f6cb1f7cc50>> repeat 9
ERROR: Invoking <bound method RenderingCanvas.on_draw of <RenderingCanvas (Glfw) at 0x7f6cb1f7cc50>> repeat 10
ERROR: Invoking <bound method RenderingCanvas.on_draw of <RenderingCanvas (Glfw) at 0x7f6cb1f7cc50>> repeat 20
➜  shadertoy-render git:(master) ✗ ls
docs  glsl  LICENSE  README.rst  Seascape.glsl  shadertoy-render.py
➜  shadertoy-render git:(master) ✗ 
```

**Comment by chaosink** [comment]
Here is the information after disabling `-loglevel panic`.
```shell
➜  shadertoy-render git:(master) ✗ python shadertoy-render.py Seascape.glsl Seascape.mp4 --size 1920x1080 --duration 5.0 --rate 10
ffmpeg version 2.7.1 Copyright (c) 2000-2015 the FFmpeg developers
  built with gcc 4.8 (Ubuntu 4.8.4-2ubuntu1~14.04)
  configuration: 
  libavutil      54. 27.100 / 54. 27.100
  libavcodec     56. 41.100 / 56. 41.100
  libavformat    56. 36.100 / 56. 36.100
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 16.101 /  5. 16.101
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  2.100 /  1.  2.100
WARNING: Traceback (most recent call last):
  File "shadertoy-render.py", line 167, in <module>
    canvas.app.run()
  File "/usr/local/lib/python2.7/dist-packages/vispy/app/application.py", line 123, in run
    return self._backend._vispy_run()
  File "/usr/local/lib/python2.7/dist-packages/vispy/app/backends/_glfw.py", line 194, in _vispy_run
    self._vispy_process_events()
  File "/usr/local/lib/python2.7/dist-packages/vispy/app/backends/_glfw.py", line 188, in _vispy_process_events
    win._on_draw()
  File "/usr/local/lib/python2.7/dist-packages/vispy/app/backends/_glfw.py", line 407, in _on_draw
    self._vispy_canvas.events.draw(region=None)  # (0, 0, w, h))
  File "/usr/local/lib/python2.7/dist-packages/vispy/util/event.py", line 436, in __call__
    self._invoke_callback(cb, event)
  File "/usr/local/lib/python2.7/dist-packages/vispy/util/event.py", line 452, in _invoke_callback
    self, cb_event=(cb, event))
  << caught exception here: >>
  File "/usr/local/lib/python2.7/dist-packages/vispy/util/event.py", line 448, in _invoke_callback
    cb(event)
  File "shadertoy-render.py", line 104, in on_draw
    self._stdout.write(framebuffer.tobytes())
AttributeError: 'numpy.ndarray' object has no attribute 'tobytes'
ERROR: Invoking <bound method RenderingCanvas.on_draw of <RenderingCanvas (Glfw) at 0x7f22a5e5ec50>> for DrawEvent
ERROR: Invoking <bound method RenderingCanvas.on_draw of <RenderingCanvas (Glfw) at 0x7f22a5e5ec50>> repeat 2
ERROR: Invoking <bound method RenderingCanvas.on_draw of <RenderingCanvas (Glfw) at 0x7f22a5e5ec50>> repeat 3
ERROR: Invoking <bound method RenderingCanvas.on_draw of <RenderingCanvas (Glfw) at 0x7f22a5e5ec50>> repeat 4
ERROR: Invoking <bound method RenderingCanvas.on_draw of <RenderingCanvas (Glfw) at 0x7f22a5e5ec50>> repeat 5
ERROR: Invoking <bound method RenderingCanvas.on_draw of <RenderingCanvas (Glfw) at 0x7f22a5e5ec50>> repeat 6
ERROR: Invoking <bound method RenderingCanvas.on_draw of <RenderingCanvas (Glfw) at 0x7f22a5e5ec50>> repeat 7
ERROR: Invoking <bound method RenderingCanvas.on_draw of <RenderingCanvas (Glfw) at 0x7f22a5e5ec50>> repeat 8
ERROR: Invoking <bound method RenderingCanvas.on_draw of <RenderingCanvas (Glfw) at 0x7f22a5e5ec50>> repeat 9
Input #0, rawvideo, from 'pipe:':
  Duration: N/A, bitrate: 663552 kb/s
    Stream #0:0: Video: rawvideo (RGBA / 0x41424752), rgba, 1920x1080, 663552 kb/s, 10 tbr, 10 tbn, 10 tbc
Unknown encoder 'libx264'
➜  shadertoy-render git:(master) ✗ 
```

**Comment by chaosink** [comment]
I googled `Unknown encoder 'libx264'` and `ffmpeg libx264` and found this: [How to quickly compile FFmpeg with libx264 (x264, H.264)](https://trac.ffmpeg.org/wiki/How%20to%20quickly%20compile%20FFmpeg%20with%20libx264%20(x264,%20H.264)). 
So I recompiled `ffmpeg` with `./configure --enable-gpl --enable-libx264`. This time the MP4 file appeared, however I couldn't play it using VLC which said `unable to identify the input format`.

**Comment by alexjc** [comment]
The `libx264` things should be resolved. There's one bug left in this project:

```
AttributeError: 'numpy.ndarray' object has no attribute 'tobytes`
```

I'll check what it's supposed to be, maybe `toarray`.

**Comment by alexjc** [comment]
Try getting latest including my fix [de66a57f1c]. Playing with VLC should work fine!

You can also use `--verbose` parameter to display `ffmpeg` output without hacking the source.

**Comment by chaosink** [comment]
I updated numpy to 1.9.2 and now it works perfectly.

The problem about duration that I posed does't exist actually. I mistook it.

Many thanks for your problem solving!

**Comment by alexjc** [comment]
The duration problem may have been related to the exception above.

Great, closing the ticket!
