### ISSUE TITLE
Module 'time' has no attribute 'clock'

### ISSUE THREAD

**Issue by AjaniBilby** [alexjc/shadertoy-render#15]
Ran the below command to get an unusual error that appears to have nothing to do with my shader or command arguments.
```
python shadertoy-render.py "U:\Documents\My Projects\Programming\Visuals\Shaders\boundry.shader" --output out.mp4 --size 1920x1080 --duration 10
Traceback (most recent call last):
  File "shadertoy-render.py", line 590, in <module>
    canvas = RenderingCanvas(glsl_shader,
  File "shadertoy-render.py", line 144, in __init__
    clock = time.clock()
AttributeError: module 'time' has no attribute 'clock'
```
For reference here is a link to the shader being rendered (https://www.shadertoy.com/view/NsGSR3)

**Comment by danilw** [comment]
try my fork of this script, it updated to python 3
https://github.com/danilw/shadertoy-to-video-with-FBO

**Comment by Indhar01** [comment]
**upgrade your sqlalchemy**
`pip install sqlalchemy --upgrade`

**Comment by yuyou** [comment]
need to change the "`time.clock()"` to "`time.process_time()`"
